#!/usr/bin/env ruby

require 'schema'
require 'xmi_parser'

Glossary = XMIParser.new

msd_files = ['../schema_dev/MTConnectAssets.msd',
			 '../schema_dev/MTConnectDevices.msd',
			 '../schema_dev/MTConnectStreams.msd',
			 '../schema_dev/MTConnectError.msd']

msd_files.each do |file|
  puts "Parsing schema for #{file}"
  schema = Schema.new File.read(file)

  %w{1.0 1.1}.each do |version|
    puts "  Generating schema for #{file} #{version}"
    doc = schema.generate_xsd(version)
    ver = "_#{version}" if version != '1.1'
    out = "../schema_dev/#{File.basename(file, '.msd')}_#{schema.version}#{ver}.xsd"
    puts "    Writing schema document: #{out}"
    File.open(out, 'w') { |f| doc.write(f, 2) }
  end
end