#!/usr/bin/env ruby

# initialize bundler and path
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)
require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])
$: << File.expand_path('../../src', __FILE__)

require 'latexify'

Dir['markdown/*.md'].each do |file|
  MarkdownConverter.generate_latex(file, 'latexed')
end