This is makeindex, version 2.15 [MiKTeX 2.9.7250 64-bit] (kpathsea + Thai support).
Scanning style file ./main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (11 comparisons).
Generating output file main.acr....done (6 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
